# Generated by Django 5.1.1 on 2024-09-15 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Основной номер телефона, включая код страны, если применимо', max_length=20, verbose_name='Номер телефона')),
                ('phone_country', models.CharField(blank=True, help_text='Страна, где зарегистрирован телефонный номер', max_length=100, null=True, verbose_name='Страна')),
                ('phone_type', models.CharField(blank=True, help_text='Тип телефона (например, мобильный, домашний, рабочий)', max_length=20, null=True, verbose_name='Тип телефона')),
                ('phone_local', models.CharField(blank=True, help_text='Локальный номер без международного кода', max_length=20, null=True, verbose_name='Локальный номер')),
                ('phone_international', models.CharField(blank=True, help_text='Полный международный номер телефона', max_length=20, null=True, verbose_name='Международный номер')),
                ('phone_carrier', models.CharField(blank=True, help_text='Оператор связи или провайдер телефонных услуг', max_length=100, null=True, verbose_name='Оператор связи')),
                ('phone_prefix', models.CharField(blank=True, help_text='Префикс телефонного номера, например, код города', max_length=20, null=True, verbose_name='Префикс')),
                ('phone_code', models.CharField(blank=True, help_text='Код телефонного номера (например, код страны или области)', max_length=20, null=True, verbose_name='Код')),
                ('user', models.ForeignKey(help_text='Пользователь, которому принадлежит этот телефонный номер', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Телефонный номер',
                'verbose_name_plural': 'Телефонные номера',
            },
        ),
    ]
