# Generated by Django 5.1.1 on 2024-09-16 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Название папки', max_length=200, verbose_name='Название папки')),
                ('description', models.TextField(blank=True, default='', help_text='Описание папки (необязательно)', null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли папка', verbose_name='Активна')),
                ('user', models.ForeignKey(help_text='Пользователь, создавший папку', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(default='', help_text='Название загруженного документа', max_length=200, verbose_name='Название документа')),
                ('file', models.FileField(help_text='Загруженный файл', upload_to='documents/%Y/%m/%d', verbose_name='Файл')),
                ('description', models.TextField(blank=True, default='', help_text='Описание документа (необязательно)', null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли документ', verbose_name='Активен')),
                ('extension', models.CharField(blank=True, help_text='Расширение загруженного файла', max_length=10, null=True, verbose_name='Расширение файла')),
                ('size', models.PositiveIntegerField(blank=True, help_text='Размер файла в байтах', null=True, verbose_name='Размер файла')),
                ('user', models.ForeignKey(help_text='Пользователь, загрузивший документ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('folder', models.ForeignKey(help_text='Папка, в которую загружен документ', on_delete=django.db.models.deletion.CASCADE, to='contents.folder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['created_at'],
            },
        ),
    ]
