# Generated by Django 5.1.1 on 2024-09-17 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='access',
            field=models.ManyToManyField(blank=True, help_text='Кому доступен документ', related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Доступ'),
        ),
    ]
